//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.02 at 03:15:48 PM IST 
//


package com.cognizant.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cognizant.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cognizant.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Terminal }
     * 
     */
    public Terminal createTerminal() {
        return new Terminal();
    }

    /**
     * Create an instance of {@link Expr }
     * 
     */
    public Expr createExpr() {
        return new Expr();
    }

    /**
     * Create an instance of {@link ColumnName }
     * 
     */
    public ColumnName createColumnName() {
        return new ColumnName();
    }

    /**
     * Create an instance of {@link SelectListExpr }
     * 
     */
    public SelectListExpr createSelectListExpr() {
        return new SelectListExpr();
    }

    /**
     * Create an instance of {@link TableName }
     * 
     */
    public TableName createTableName() {
        return new TableName();
    }

    /**
     * Create an instance of {@link SelectList }
     * 
     */
    public SelectList createSelectList() {
        return new SelectList();
    }

    /**
     * Create an instance of {@link FromClause }
     * 
     */
    public FromClause createFromClause() {
        return new FromClause();
    }

    /**
     * Create an instance of {@link SelectExpr }
     * 
     */
    public SelectExpr createSelectExpr() {
        return new SelectExpr();
    }

    /**
     * Create an instance of {@link SelectStmt }
     * 
     */
    public SelectStmt createSelectStmt() {
        return new SelectStmt();
    }

    /**
     * Create an instance of {@link SqlStmt }
     * 
     */
    public SqlStmt createSqlStmt() {
        return new SqlStmt();
    }

    /**
     * Create an instance of {@link SqlStmtList }
     * 
     */
    public SqlStmtList createSqlStmtList() {
        return new SqlStmtList();
    }

    /**
     * Create an instance of {@link Parse }
     * 
     */
    public Parse createParse() {
        return new Parse();
    }

}
