//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.02 at 03:15:48 PM IST 
//


package com.cognizant.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}select_expr"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "selectExpr"
})
@XmlRootElement(name = "select_stmt")
public class SelectStmt {

    @XmlElement(name = "select_expr", required = true)
    protected SelectExpr selectExpr;

    /**
     * Gets the value of the selectExpr property.
     * 
     * @return
     *     possible object is
     *     {@link SelectExpr }
     *     
     */
    public SelectExpr getSelectExpr() {
        return selectExpr;
    }

    /**
     * Sets the value of the selectExpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectExpr }
     *     
     */
    public void setSelectExpr(SelectExpr value) {
        this.selectExpr = value;
    }

}
