//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.02 at 03:15:48 PM IST 
//


package com.cognizant.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}terminal"/&gt;
 *         &lt;element ref="{}select_list"/&gt;
 *         &lt;element ref="{}from_clause"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "terminal",
    "selectList",
    "fromClause"
})
@XmlRootElement(name = "select_expr")
public class SelectExpr {

    @XmlElement(required = true)
    protected Terminal terminal;
    @XmlElement(name = "select_list", required = true)
    protected SelectList selectList;
    @XmlElement(name = "from_clause", required = true)
    protected FromClause fromClause;

    /**
     * Gets the value of the terminal property.
     * 
     * @return
     *     possible object is
     *     {@link Terminal }
     *     
     */
    public Terminal getTerminal() {
        return terminal;
    }

    /**
     * Sets the value of the terminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terminal }
     *     
     */
    public void setTerminal(Terminal value) {
        this.terminal = value;
    }

    /**
     * Gets the value of the selectList property.
     * 
     * @return
     *     possible object is
     *     {@link SelectList }
     *     
     */
    public SelectList getSelectList() {
        return selectList;
    }

    /**
     * Sets the value of the selectList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectList }
     *     
     */
    public void setSelectList(SelectList value) {
        this.selectList = value;
    }

    /**
     * Gets the value of the fromClause property.
     * 
     * @return
     *     possible object is
     *     {@link FromClause }
     *     
     */
    public FromClause getFromClause() {
        return fromClause;
    }

    /**
     * Sets the value of the fromClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link FromClause }
     *     
     */
    public void setFromClause(FromClause value) {
        this.fromClause = value;
    }

}
