//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.02 at 03:15:48 PM IST 
//


package com.cognizant.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{}select_list_expr"/&gt;
 *         &lt;element ref="{}terminal"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "selectListExprOrTerminal"
})
@XmlRootElement(name = "select_list")
public class SelectList {

    @XmlElements({
        @XmlElement(name = "select_list_expr", type = SelectListExpr.class),
        @XmlElement(name = "terminal", type = Terminal.class)
    })
    protected List<Object> selectListExprOrTerminal;

    /**
     * Gets the value of the selectListExprOrTerminal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectListExprOrTerminal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectListExprOrTerminal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectListExpr }
     * {@link Terminal }
     * 
     * 
     */
    public List<Object> getSelectListExprOrTerminal() {
        if (selectListExprOrTerminal == null) {
            selectListExprOrTerminal = new ArrayList<Object>();
        }
        return this.selectListExprOrTerminal;
    }

}
